# ----
# Site

title: Mappit
url: "https://mappit.app"
baseurl:
sign_up_url: https://dashboard.mappit.app/auth/register
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:
show_testimonial: false

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Product marketing template for Jekyll.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Mappit API
  links:
    - https://twitter.com/mappitapi

# -----
# Build

timezone: Australia/Melbourne

collections:
  staff_members:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  - scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "index.html"
    values:
      layout: "default"
  - scope:
      path: "contact.html"
    values:
      full_width: true

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_select_data:
  social_icons:
    - Facebook
    - Instagram
    - LinkedIn
    - Pinterest
    - Tumblr
    - Twitter
    - YouTube
    - RSS

_comments:
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  pricing_table: Update the information in the pricing tables.
  highlight: Emphasis the text
  color: The background colour used in the plan name and call to action.
  new_window: Open link in new window

pricing_table:
- name: Pay as you go
  color: "#8e8e8e"
  features:
    - text: Tiered pricing
      highlight: true
    - text: Requests averaged over the whole month
      highlight: false
    - text: "0-30,000 requests per month: free!"
      highlight: false
    - text: "30,001-100,000 requests: $3 per 10,000"
      highlight: false
    - text: "100,001-300,000 requests: $1.50 per 10,000"
      highlight: false
    - text: "300,001+ requests: $0.80 per 10,000"
      hightlight: false
  call_to_action:
    link: https://dashboard.mappit.app/auth/register
    text: Get started
- name: Enterprise
  color: "#000000"
  features:
    - text: Contact Us
      highlight: true
    - text: Unlimited Requests
      highlight: false
  call_to_action:
    link: mailto:info@mappit.app
    text: Contact Us
